### ISSUE TITLE
Incompatible with "Trim Trailing Whitespace" preference

### ISSUE THREAD

**Issue by bkroeker** [douglashill/nova-autosave#2]
There is an option in `Preferences > Editor > Indentation > Saving > Automatically trim trailing whitespace` which, when combined with this extension, causes the inability to type new words or new lines.  The extension immediately eliminates any spaces or tabs as you type them.  

Perhaps this extension could save a little less aggressively -- maybe just when the file loses focus, for example?  This is a feature I miss from Sublime Text.

**Comment by bkroeker** [comment]
Following up, this is also an issue if you have other code formatters present.  For example, I can't use the prettier extension for javascript because nova-autosave keeps causing prettier to delete the newline I'm trying to add.  Again, a save on focus loss would seem more appropriate in this case.

**Comment by douglashill** [comment]
I agree saving on the editor losing focus would be better. However I haven’t found any API for Nova extensions to do this. If you find any API like that I‘d love to know. I’ve looked through https://docs.nova.app/api-reference/text-editor/ and some related API.

Unless Panic adds this, I think the only workaround we could consider would be saving after a slight delay. This doesn’t really fix the problem though — it would still get rid of the trailing white space if you take a while before typing the next key. However if the delay is several seconds it might be good enough.

**Comment by liam-k** [comment]
Hi! I had similar problems with the plugin saving a bit too eagerly, and I also disliked the immediate saving when I was running a live-server that updates on every save – can get a bit distracting when it constantly rebuilds. 

So I modified the plugin on my machine and added some functionality and settings to enable a "classic" autosaving mode, where it just saves every few minutes (or whatever interval you choose). I think it’s the easiest way to mitigate all kinds of problems like that.

Not sure if you’d prefer to keep your script a "pure" continuous saving plugin, but If you’re open to adding that functionality, I could clean my version up a bit and submit a pull request. :)

**Comment by douglashill** [comment]
Thanks @liam-k — I‘d definitely be interested in trying out your modifications if you can push them to a fork. Personally my preference would be to save nearly continuously but throttle it a bit since the immediate saving causes all these problems, so I’d like to see how your version works if the internal was set to something like 5 seconds.

**Comment by liam-k** [comment]
Alright, [I forked it](https://github.com/liam-k/nova-autosave). Hope it all makes sense! You can set the interval to pretty much anything (above 1 second) in preferences. Only thing that’s still missing is an event listener for the preferences, so right now you have to quickly disable and enable the plugin again if you want any changed settings to take effect.

**Comment by douglashill** [comment]
I published version 2, which saves after a 3 second delay when you stop editing.

I think this is enough to mitigate the problems with with trimming trailing whitespace and formatting. The formatting will still kick in automatically, but the delay should means this is substantially less problematic because you at least have time to finish what you were trying to type.

@liam-k thank you for your fork. This looks like good option in your case of not wanting to keep reloading a local server. I decided to keep mine focused on continuously saving since I think the delay resolves the main issues with it.

Sorry for the delay on this!

**Comment by liam-k** [comment]
Thanks for the update! Makes sense for you to keep it continuuous only. Would you mind if I released my own plugin based on the fork? I think it might be useful for other people who want to toggle between both ways of saving or set their own custom delay – I was thinking of maybe making it possible to switch between the two modes on a per-project basis as well.

**Comment by douglashill** [comment]
@liam-k I wouldn’t mind at all. It’s such a small amount of code please go ahead and publish it as you like. (Just make sure you change the identifier etc. to your name.)
